// <auto-generated />
namespace NguyenThiNgocBich329.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class createtable_loaissp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtable_loaissp));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210620598_create-table_loaissp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
