// <auto-generated />
namespace NguyenThiNgocBich329.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class create_table_ncc_nguyenthingocbich0329 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_table_ncc_nguyenthingocbich0329));
        
        string IMigrationMetadata.Id
        {
            get { return "202112210607527_create_table_ncc_nguyenthingocbich0329"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
